// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_rooms_roomId_ai_participants_run from "./routes/api/rooms/[roomId]/ai-participants/run.ts";
import * as $api_rooms_roomId_prompt_generate from "./routes/api/rooms/[roomId]/prompt/generate.ts";
import * as $index from "./routes/index.tsx";
import * as $rooms_id_ from "./routes/rooms/[id].tsx";
import * as $HomeApp from "./islands/HomeApp.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $RoomLobby from "./islands/RoomLobby.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/rooms/[roomId]/ai-participants/run.ts":
      $api_rooms_roomId_ai_participants_run,
    "./routes/api/rooms/[roomId]/prompt/generate.ts":
      $api_rooms_roomId_prompt_generate,
    "./routes/index.tsx": $index,
    "./routes/rooms/[id].tsx": $rooms_id_,
  },
  islands: {
    "./islands/HomeApp.tsx": $HomeApp,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/RoomLobby.tsx": $RoomLobby,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
